module.exports.breakfast = {
  Bagels: 1,
  Bakery: 1,
  Breakfast: 1,
  Cafe: 1,
  Crepes: 1,
  Diner: 1,
  Donuts: 1,
  Patisserie: 1,
  Southern: 1,
  Vegetarian: 1,
};

module.exports.other = {
  Afghani: 1,
  African: 1,
  American: 1,
  Amish: 1,
  Argentine: 1,
  Armenian: 1,
  Asian: 1,
  Australian: 1,
  Austrian: 1,
  BBQ: 1,
  'Bar Food': 1,
  Belgian: 1,
  Brazilian: 1,
  British: 1,
  Burger: 1,
  Burmese: 1,
  Cajun: 1,
  California: 1,
  Cambodian: 1,
  Canadian: 1,
  Cantonese: 1,
  Caribbean: 1,
  'Central Asian': 1,
  Chilean: 1,
  Chilean: 1,
  Chinese: 1,
  Colombian: 1,
  Creole: 1,
  Cuban: 1,
  Danish: 1,
  Deli: 1,
  'Dim Sum': 1,
  Diner: 1,
  'Eastern European': 1,
  Ecuadorian: 1,
  Ethiopian: 1,
  European: 1,
  Filipino: 1,
  'Fish and Chips': 1,
  Fondue: 1,
  French: 1,
  Fusion: 1,
  Georgian: 1,
  German: 1,
  Greek: 1,
  Hawaiian: 1,
  'Healthy Food': 1,
  Hungarian: 1,
  Indian: 1,
  Indonesian: 1,
  International: 1,
  Irish: 1,
  Israeli: 1,
  Italian: 1,
  Jamaican: 1,
  Japanese: 1,
  Jewish: 1,
  Juices: 1,
  Kebab: 1,
  Korean: 1,
  Laotian: 1,
  'Latin American': 1,
  Lebanese: 1,
  Malaysian: 1,
  Mediterranean: 1,
  Mexican: 1,
  'Middle Eastern': 1,
  Mongolian: 1,
  Moroccan: 1,
  Mughlai: 1,
  Nepalese: 1,
  'New American': 1,
  'New Mexican': 1,
  'New Zealand': 1,
  Pacific: 1,
  'Pacific Northwest': 1,
  Pakistani: 1,
  Persian: 1,
  Peruvian: 1,
  Pizza: 1,
  "Po'Boys": 1,
  Polish: 1,
  Portuguese: 1,
  'Pub Food': 1,
  'Puerto Rican': 1,
  Ramen: 1,
  Russian: 1,
  Salad: 1,
  Salvadorean: 1,
  Sandwich: 1,
  Scandinavian: 1,
  Scottish: 1,
  Seafood: 1,
  Sichuan: 1,
  Singaporean: 1,
  Somali: 1,
  'Soul Food': 1,
  'South African': 1,
  'South American': 1,
  Southern: 1,
  Southwestern: 1,
  Spanish: 1,
  'Sri Lankan': 1,
  Steak: 1,
  Sushi: 1,
  Swedish: 1,
  Taco: 1,
  Taiwanese: 1,
  Tapas: 1,
  Teriyaki: 1,
  'Tex-Mex': 1,
  Thai: 1,
  Tibetan: 1,
  Tunisian: 1,
  Turkish: 1,
  Ukranian: 1,
  Uruguayan: 1,
  Vegetarian: 1,
  Venezuelan: 1,
  Vietnamese: 1,
  Welsh: 1,
};
